### ISSUE TITLE
Get this going ;)

### ISSUE THREAD

**Issue by kristianmandrup** [feathersjs/feathers-android#1]
What can we do to help get this going ;)
Perhaps use some kind of starter template?

**Comment by corymsmith** [comment]
@kristianmandrup I'll check in some of the code that I've started so we can collab!

**Comment by kristianmandrup** [comment]
Awesome! I'd like to use FeathersJS from a FuseJS app, using Web sockets.

**Comment by corymsmith** [comment]
Just submitted #2 that is a decent start, still a bunch to work through but basic stuff like auth and fetching data from a service is working + listening for service events using sockets.

**Comment by kristianmandrup** [comment]
Great! Thanks a lot :)
